export { default as waitingForCarUpdate } from "./waitingForCarUpdate";
export { default as callCar } from "./callCar";
export { default as carCame } from "./carCame";
export { default as disappearStickmans } from "./disappearStickmans";
export { default as getStickmansIntoCar } from "./getStickmansIntoCar";
export { default as addStickmansOnFloor } from "./addStickmansOnFloor";
export { default as reorderStickmansAfterGetIn } from "./reorderStickmansAfterGetIn";
export { default as assignCars } from "./assignCars";
export { default as theNearestCar } from "./theNearestCar";
